apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kured
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubereboot.github.io/charts
    chart: kured
    targetRevision: 5.6.1
    helm:
      values: |
        configuration:
          timeZone: "UTC"
          startTime: "18:00"
          endTime: "23:00"
          rebootDays: [su, mo, tu, we, th, fr, sa]
          rebootSentinel: "/var/run/reboot-needed"
          period: "1h0m0s"

        maxUnavailable: 1
        updateStrategy: "RollingUpdate"

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
